# Generated by Django 4.2 on 2023-05-21 16:37

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Psot',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('9ce90912-2825-47b2-a909-2e667896cc73'), primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='post_images')),
                ('upload_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
